# Generated by Django 3.2.5 on 2021-07-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('original_picture', models.BinaryField(blank=True, null=True)),
                ('sized_picture', models.BinaryField(blank=True, null=True)),
                ('content_type', models.CharField(blank=True, max_length=256)),
            ],
        ),
    ]
