# Generated by Django 3.2.5 on 2021-07-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='original_picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='sized_picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
