# Generated by Django 3.2.5 on 2021-07-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_exchange', '0003_auto_20210701_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='original_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picture',
            name='original_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='original_picture',
            field=models.ImageField(height_field='original_height', upload_to='site_media', width_field='original_width'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='sized_picture',
            field=models.ImageField(null=True, upload_to='site_media'),
        ),
    ]
