# Generated by Django 3.2.5 on 2021-07-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic_exchange', '0004_auto_20210702_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='original_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='picture',
            name='original_width',
            field=models.IntegerField(null=True),
        ),
    ]
